### ISSUE TITLE
Questions about the matmul function in run.c

### ISSUE THREAD

**Issue by KangkangStu** [RahulSChand/llama2.c-for-dummies#3]
As a newcomer to transformers, there are some questions about the matrix multiplication operator in run.c, can the author answer them.
![image](https://github.com/RahulSChand/llama2.c-for-dummies/assets/124141787/93e92c5c-1ea8-4802-a877-e65bc83a0849)
In the forward function, it can be seen that the matmul function is called when calculating qkv, but the actual matmul is done with the calculation of a one-dimensional vector multiplied matrix, so the resulting qkv is also a 1*dim vector. But shouldn't qkv be a two-dimensional matrix in the transformer I'm exposed to? There is a little doubt here, I hope the author can answer it!! thanks！

**Comment by RahulSChand** [comment]
@KangkangStu you are correct that ideally the matmul would be `(d, d) x (d, n)` so the output should be `d x n` a 2-d vector. But in this `run.c` we process tokens one at a time only, so `n=1` always. Therefore the matmul becomes `(d x d) x (d,1) = (d,1)` which is a 1-d vector.

In the `void matmul(float* xout, float* x, float* w, int n, int d)` function we explicitly assume that we will be matmuling a 2-d matrix (`dxd`) with a 1-d matrix (`dx1`)

**Comment by KangkangStu** [comment]
> @KangkangStu你是对的，理想情况下 matmul 应该是`(d, d) x (d, n)`这样，输出应该是`d x n`一个二维向量。但在这种情况下，`run.c`我们每次只处理一个令牌，所以`n=1`总是如此。因此，matmul 变为`(d x d) x (d,1) = (d,1)`一维向量。
> 
> 在`void matmul(float* xout, float* x, float* w, int n, int d)`函数中，我们明确假设我们将二维矩阵 ( `dxd`) 与一维矩阵 ( `dx1`)进行矩阵乘法

Thank you for your reply, it helped me a lot. Have a good life！

**Comment by KangkangStu** [comment]
> @KangkangStu你是对的，理想情况下 matmul 应该是`(d, d) x (d, n)`这样，输出应该是`d x n`一个二维表示。但在这种情况下，`run.c`我们每次只处理一个令牌，所以`n=1`总是如此。因此，matmul 变为`(d x d) x (d,1) = (d,1)`一维表示。
> 
> 在`void matmul(float* xout, float* x, float* w, int n, int d)`函数中，我们明确地假设我们将二维矩阵 ( `dxd`) 与一维矩阵 ( `dx1`) 进行矩阵乘法

In addition, I would like to ask how to implement a matrix multiplication operation if the prompt is entered for the first time. For example, if I give some prompts, it should not be a vector multiplication matrix
